### ISSUE TITLE
10000000th milestone message not displayed

### ISSUE THREAD

**Issue by ilia-21** [juxtopposed/touchgrass#8]
10000000th milestone message did not show up once I reached 10M clicks. 
This is probably because there's no 10000000 in the milestones array
https://github.com/juxtopposed/touchgrass/blob/d3514eb61257893b597626f665a3f2506e91a596/index.html#L87
(don't ask me how I know this)

**Comment by juxtopposed** [comment]
sorry for the inconvenience. i understand how disappointing it must've been to touch grass 10 million times and not be rewarded. this is fixed now, so you can try touching grass 10 million times again, and you should see the milestone message this time.

**Comment by ilia-21** [comment]
YES, FINALLY 
Now I just need to reset my browser data and click 10M times again to check it out
